version: ${APP_VERSION}

services:

  # database service
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_PGDATA}
    volumes:
      - ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    env_file:
      - .env